/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Cast {
  id: number;
  name: string;
  gender: number;
  character: string;
  profile_path: string | null;
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}
