/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Movie {
  id: number;
  title: string;
  backdrop_path: string | null;
  poster_path: string | null;
  release_date?: string;
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}
